language: node_js
node_js:
  - stable

script:
  - nyc npm test
  - nyc report --reporter=text-lcov --exclude "./models/platforms/codechef.js" > coverage.lcov
after_success:
  - ./node_modules/.bin/codecov